[build]
  publish = "public"
  command = "npm install"
  ignore = "exit 0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
